apiVersion: v2
name: keycloak-opensearch-deployment
description: Despliegue mediante Helm chart para Keycloak, OpenSearch, y Opensearch-Dashboards con gestión de ingres Nginx usando Charts de Bitnami como base.
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: nginx-ingress-controller
    version: "11.6.25"
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: ingress-controller
    condition: ingress-controller.enabled

  - name: keycloak
    version: "24.7.4"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: keycloak.enabled

  - name: opensearch
    version: "2.0.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: opensearch.enabled

keywords:
  - keycloak
  - opensearch
  - ingress
  - authentication
  - search
  - bitnami
